#!/usr/bin/env bash

mkdir -p /srv/workspace/ 2>/dev/null
cd /srv/workspace

recataargs=$1
source1=$2
source2=$3
source3=$4

rm -rf $recatargs || echo "Failed to remove content in $recatargs"

git -C "$recataargs" clone "$source1"/"$source2" || logger "recurse-catalog error during repo clone"

/usr/local/bin/recata $recataargs
/usr/local/bin/source-data $source1 $source2 $source3

filemod="$(ls -larth *catalog.csv | tail -n1 | rev | awk '{print $1}' | rev)"
append="$(cat $(ls -larth *url.dat | tail -n1 | rev | awk '{print $1}' | rev | cut -d',' -f2-) | cut -d',' -f1,3-)"
:>load.csv
cat $filemod | while read line; do
  echo "$line,$append" >> load.csv
done
